// This file is auto-generated by CMake
// Any changes made to this file will be lost
// Set major, minor and revision numbers in the root CMakeLists.txt file

#ifndef VERSION_AUTOGEN_H
#define VERSION_AUTOGEN_H

#define CMAKE_GENERATED_VERSION

#define MAJOR_VERSION 0
#define MINOR_VERSION 0
#define REVISION 1

#define BUILD_NUMBER 73
#define COMMIT_HASH "81d77db2695a864bbd229643a0158207984a8456"

#endif // VERSION_AUTOGEN_H
